In [16]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [17]:
url = 'https://fbref.com/en/comps/9/Premier-League-Stats'

In [18]:
page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [19]:
table = soup.find('table')

In [20]:
table_heads = table.find_all('th', class_ ="poptip")

In [21]:
column = [head.text.strip() for head in table_heads]

column = column[0:-1]

In [22]:
df = pd.DataFrame(columns=column)

df

Empty DataFrame
Columns: [Rk, Squad, MP, W, D, L, GF, GA, GD, Pts, Pts/MP, xG, xGA, xGD, xGD/90, Last 5, Attendance, Top Team Scorer, Goalkeeper]
Index: []

In [23]:
table_data = table.find_all('tr')

In [24]:
for data in table_data[1:]:
    row_data = data.find_all('td')
    ind_data = [rdata.text.strip() for rdata in row_data]
    team = data.find('th')
    ind_data = [team, *ind_data[0:-1]]
    length = len(df)
    df.loc[length] = ind_data
    
df

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper
0,[1],Liverpool,20,13,6,1,43,18,+25,45,2.25,44.1,22.6,+21.5,+1.08,W D D W W,"46,872",Mohamed Salah - 14,Alisson
1,[2],Aston Villa,20,13,3,4,43,27,+16,42,2.10,36.0,25.6,+10.3,+0.52,W W D L W,"28,969",Ollie Watkins - 9,Emiliano Martínez
2,[3],Manchester City,19,12,4,3,45,21,+24,40,2.11,36.8,17.8,+18.9,+1.00,L W D W W,"47,396",Erling Haaland - 14,Ederson
3,[4],Arsenal,20,12,4,4,37,20,+17,40,2.00,36.4,16.3,+20.0,+1.00,L W D L L,"60,169",Bukayo Saka - 6,David Raya
4,[5],Tottenham,20,12,3,5,42,29,+13,39,1.95,35.2,34.7,+0.4,+0.02,W W W L W,"61,624",Son Heung-min - 12,Guglielmo Vicario
5,[6],West Ham,20,10,4,6,33,30,+3,34,1.70,27.7,35.3,-7.6,-0.38,L W W W D,"62,660",Jarrod Bowen - 11,Alphonse Areola
6,[7],Brighton,20,8,7,5,38,33,+5,31,1.55,35.1,29.6,+5.5,+0.27,D L D W D,"31,604",João Pedro - 7,Jason Steele
7,[8],Manchester Utd,20,10,1,9,22,27,-5,31,1.55,29.1,32.5,-3.4,-0.17,L D L W L,"73,514",Scott McTominay - 5,André Onana
8,[9],Newcastle Utd,20,9,2,9,39,29,+10,29,1.45,39.2,33.5,+5.7,+0.29,L W L L L,"52,086",Alexander Isak - 9,Nick Pope
9,[10],Chelsea,20,8,4,8,34,31,+3,28,1.40,39.4,28.8,+10.6,+0.53,L W L W W,"39,720",Cole Palmer - 8,Robert Sánchez
10,[11],Wolves,20,8,4,8,30,31,-1,28,1.40,26.6,33.1,-6.5,-0.32,D L W W W,"31,390",Hwang Hee-chan - 10,José Sá
11,[12],Bournemouth,19,7,4,8,28,35,-7,25,1.32,27.0,31.4,-4.3,-0.23,W W W W L,"11,027",Dominic Solanke - 12,Neto
12,[13],Fulham,20,7,3,10,28,35,-7,24,1.20,24.4,34.3,-9.9,-0.50,W L L L W,"24,243",Raúl Jiménez - 5,Bernd Leno
13,[14],Crystal Palace,20,5,6,9,22,29,-7,21,1.05,24.6,28.6,-4.0,-0.20,L D D L W,"24,902",Odsonne Édouard - 6,Sam Johnstone
14,[15],Nott'ham Forest,20,5,5,10,24,35,-11,20,1.00,23.8,30.8,-7.0,-0.35,D L L W W,"29,289",Chris Wood - 7,Matt Turner
15,[16],Brentford,19,5,4,10,26,31,-5,19,1.00,32.6,25.2,+7.3,+0.39,L L L L L,"17,057",Bryan Mbeumo - 7,Mark Flekken
16,[17],Everton,20,8,2,10,24,28,-4,16,0.80,30.1,27.7,+2.4,+0.12,W W L L L,"39,086",Abdoulaye Doucouré - 6,Jordan Pickford
17,[18],Luton Town,19,4,3,12,23,37,-14,15,0.79,19.2,38.5,-19.3,-1.02,L L W W L,"9,810",Elijah Adebayo - 5,Thomas Kaminski
18,[19],Burnley,20,3,2,15,20,41,-21,11,0.55,17.4,34.5,-17.0,-0.85,D L W L L,"21,557",Lyle Foster - 4,James Trafford
19,[20],Sheffield Utd,20,2,3,15,15,49,-34,9,0.45,16.2,39.9,-23.7,-1.18,W L D L L,"30,694","Oliver McBurnie, Cameron Archer - 3",Wes Foderingham

In [25]:
import numpy as np

df['Rk'] = pd.Series(np.arange(1,21))

In [26]:
df.columns

Index(['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP',
       'xG', 'xGA', 'xGD', 'xGD/90', 'Last 5', 'Attendance', 'Top Team Scorer',
       'Goalkeeper'],
      dtype='object')

In [27]:
df['Attendance'] = df['Attendance'].apply(lambda x: x.replace(',', ''))

In [28]:
to_num = ['Rk', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'xG', 'xGA', 'xGD', 'xGD/90', 'Attendance']

df[to_num] = df[to_num].apply(pd.to_numeric)

In [29]:
df

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper
0,1,Liverpool,20,13,6,1,43,18,25,45,2.25,44.1,22.6,21.5,1.08,W D D W W,46872,Mohamed Salah - 14,Alisson
1,2,Aston Villa,20,13,3,4,43,27,16,42,2.10,36.0,25.6,10.3,0.52,W W D L W,28969,Ollie Watkins - 9,Emiliano Martínez
2,3,Manchester City,19,12,4,3,45,21,24,40,2.11,36.8,17.8,18.9,1.00,L W D W W,47396,Erling Haaland - 14,Ederson
3,4,Arsenal,20,12,4,4,37,20,17,40,2.00,36.4,16.3,20.0,1.00,L W D L L,60169,Bukayo Saka - 6,David Raya
4,5,Tottenham,20,12,3,5,42,29,13,39,1.95,35.2,34.7,0.4,0.02,W W W L W,61624,Son Heung-min - 12,Guglielmo Vicario
5,6,West Ham,20,10,4,6,33,30,3,34,1.70,27.7,35.3,-7.6,-0.38,L W W W D,62660,Jarrod Bowen - 11,Alphonse Areola
6,7,Brighton,20,8,7,5,38,33,5,31,1.55,35.1,29.6,5.5,0.27,D L D W D,31604,João Pedro - 7,Jason Steele
7,8,Manchester Utd,20,10,1,9,22,27,-5,31,1.55,29.1,32.5,-3.4,-0.17,L D L W L,73514,Scott McTominay - 5,André Onana
8,9,Newcastle Utd,20,9,2,9,39,29,10,29,1.45,39.2,33.5,5.7,0.29,L W L L L,52086,Alexander Isak - 9,Nick Pope
9,10,Chelsea,20,8,4,8,34,31,3,28,1.40,39.4,28.8,10.6,0.53,L W L W W,39720,Cole Palmer - 8,Robert Sánchez
10,11,Wolves,20,8,4,8,30,31,-1,28,1.40,26.6,33.1,-6.5,-0.32,D L W W W,31390,Hwang Hee-chan - 10,José Sá
11,12,Bournemouth,19,7,4,8,28,35,-7,25,1.32,27.0,31.4,-4.3,-0.23,W W W W L,11027,Dominic Solanke - 12,Neto
12,13,Fulham,20,7,3,10,28,35,-7,24,1.20,24.4,34.3,-9.9,-0.50,W L L L W,24243,Raúl Jiménez - 5,Bernd Leno
13,14,Crystal Palace,20,5,6,9,22,29,-7,21,1.05,24.6,28.6,-4.0,-0.20,L D D L W,24902,Odsonne Édouard - 6,Sam Johnstone
14,15,Nott'ham Forest,20,5,5,10,24,35,-11,20,1.00,23.8,30.8,-7.0,-0.35,D L L W W,29289,Chris Wood - 7,Matt Turner
15,16,Brentford,19,5,4,10,26,31,-5,19,1.00,32.6,25.2,7.3,0.39,L L L L L,17057,Bryan Mbeumo - 7,Mark Flekken
16,17,Everton,20,8,2,10,24,28,-4,16,0.80,30.1,27.7,2.4,0.12,W W L L L,39086,Abdoulaye Doucouré - 6,Jordan Pickford
17,18,Luton Town,19,4,3,12,23,37,-14,15,0.79,19.2,38.5,-19.3,-1.02,L L W W L,9810,Elijah Adebayo - 5,Thomas Kaminski
18,19,Burnley,20,3,2,15,20,41,-21,11,0.55,17.4,34.5,-17.0,-0.85,D L W L L,21557,Lyle Foster - 4,James Trafford
19,20,Sheffield Utd,20,2,3,15,15,49,-34,9,0.45,16.2,39.9,-23.7,-1.18,W L D L L,30694,"Oliver McBurnie, Cameron Archer - 3",Wes Foderingham

In [30]:
df.to_csv(r'C:\Users\Owner\OneDrive\Desktop\Python\Arsenal Data Scraping\PL_Data_23_24.csv', index=False)

In [31]:
url = 'https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures'

In [32]:
page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [83]:
table = soup.find(id='sched_2023-2024_9_1')

In [84]:
table_heads = table.find_all('th', class_ ="poptip")

In [85]:
column = [head.text.strip() for head in table_heads]

column = column[3:-2]

In [86]:
df = pd.DataFrame(columns=column)

df

Empty DataFrame
Columns: [Time, Home, xG, Score, xG, Away, Attendance, Venue, Referee]
Index: []

In [87]:
table_data = table.find_all('tr')

In [88]:
for data in table_data[1:]:
    row_data = data.find_all('td')
    ind_data = [rdata.text.strip() for rdata in row_data]
    ind_data = ind_data[2:-2]
    
    length = len(df)
    df.loc[length] = ind_data
    
df

,Time,Home,xG,Score,xG,Away,Attendance,Venue,Referee
0,20:00,Burnley,0.3,0–3,1.9,Manchester City,"21,572",Turf Moor,Craig Pawson
1,12:30,Arsenal,0.8,2–1,1.2,Nott'ham Forest,"59,984",Emirates Stadium,Michael Oliver
2,15:00,Everton,2.7,0–1,1.5,Fulham,"39,940",Goodison Park,Stuart Attwell
3,15:00,Sheffield Utd,0.5,0–1,1.9,Crystal Palace,"31,194",Bramall Lane,John Brooks
4,15:00,Brighton,4.0,4–1,1.5,Luton Town,"31,872",The American Express Community Stadium,David Coote
...,...,...,...,...,...,...,...,...,...
413,,Brentford,,,,Newcastle Utd,,Gtech Community Stadium,
414,,Chelsea,,,,Bournemouth,,Stamford Bridge,
415,,Crystal Palace,,,,Aston Villa,,Selhurst Park,
416,,Liverpool,,,,Wolves,,Anfield,
417,,Burnley,,,,Nott'ham Forest,,Turf Moor,

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Time        418 non-null    object
 1   Home        418 non-null    object
 2   xG          418 non-null    object
 3   Score       418 non-null    object
 4   xG          418 non-null    object
 5   Away        418 non-null    object
 6   Attendance  418 non-null    object
 7   Venue       418 non-null    object
 8   Referee     418 non-null    object
dtypes: object(9)
memory usage: 32.7+ KB

In [90]:
df = df.drop(df[df['Score'] == ''].index)

In [91]:
df[['Home_Goals', 'Away_Goals']] = df['Score'].str.split('–', expand=True)

In [92]:
df

,Time,Home,xG,Score,xG,Away,Attendance,Venue,Referee,Home_Goals,Away_Goals
0,20:00,Burnley,0.3,0–3,1.9,Manchester City,"21,572",Turf Moor,Craig Pawson,0,3
1,12:30,Arsenal,0.8,2–1,1.2,Nott'ham Forest,"59,984",Emirates Stadium,Michael Oliver,2,1
2,15:00,Everton,2.7,0–1,1.5,Fulham,"39,940",Goodison Park,Stuart Attwell,0,1
3,15:00,Sheffield Utd,0.5,0–1,1.9,Crystal Palace,"31,194",Bramall Lane,John Brooks,0,1
4,15:00,Brighton,4.0,4–1,1.5,Luton Town,"31,872",The American Express Community Stadium,David Coote,4,1
...,...,...,...,...,...,...,...,...,...,...,...
215,17:30,Nott'ham Forest,0.7,2–1,0.8,Manchester Utd,"29,529",The City Ground,Tim Robinson,2,1
216,14:00,Tottenham,2.3,3–1,1.7,Bournemouth,"61,780",Tottenham Hotspur Stadium,Simon Hooper,3,1
217,14:00,Fulham,1.2,2–1,1.6,Arsenal,"24,444",Craven Cottage,Joshua Smith,2,1
218,20:00,Liverpool,7.0,4–2,0.6,Newcastle Utd,,Anfield,Anthony Taylor,4,2
219,19:30,West Ham,0.7,0–0,2.4,Brighton,"62,462",London Stadium,Samuel Barrott,0,0

In [93]:
df['Attendance'] = df['Attendance'].apply(lambda x: x.replace(',', ''))

In [94]:
to_num = ['Attendance', 'Home_Goals', 'Away_Goals']

df['xG'] = df['xG'].apply(pd.to_numeric)
df[to_num] = df[to_num].apply(pd.to_numeric)
df = df.drop(columns=['Score'])

In [95]:
df

,Time,Home,xG,xG,Away,Attendance,Venue,Referee,Home_Goals,Away_Goals
0,20:00,Burnley,0.3,1.9,Manchester City,21572.0,Turf Moor,Craig Pawson,0,3
1,12:30,Arsenal,0.8,1.2,Nott'ham Forest,59984.0,Emirates Stadium,Michael Oliver,2,1
2,15:00,Everton,2.7,1.5,Fulham,39940.0,Goodison Park,Stuart Attwell,0,1
3,15:00,Sheffield Utd,0.5,1.9,Crystal Palace,31194.0,Bramall Lane,John Brooks,0,1
4,15:00,Brighton,4.0,1.5,Luton Town,31872.0,The American Express Community Stadium,David Coote,4,1
...,...,...,...,...,...,...,...,...,...,...
215,17:30,Nott'ham Forest,0.7,0.8,Manchester Utd,29529.0,The City Ground,Tim Robinson,2,1
216,14:00,Tottenham,2.3,1.7,Bournemouth,61780.0,Tottenham Hotspur Stadium,Simon Hooper,3,1
217,14:00,Fulham,1.2,1.6,Arsenal,24444.0,Craven Cottage,Joshua Smith,2,1
218,20:00,Liverpool,7.0,0.6,Newcastle Utd,NaN,Anfield,Anthony Taylor,4,2
219,19:30,West Ham,0.7,2.4,Brighton,62462.0,London Stadium,Samuel Barrott,0,0

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 199 entries, 0 to 219
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Time        199 non-null    object
 1   Home        199 non-null    object
 2   xG          198 non-null    float64
 3   xG          198 non-null    float64
 4   Away        199 non-null    object
 5   Attendance  193 non-null    float64
 6   Venue       199 non-null    object
 7   Referee     199 non-null    object
 8   Home_Goals  199 non-null    int64
 9   Away_Goals  199 non-null    int64
dtypes: float64(3), int64(2), object(5)
memory usage: 17.1+ KB

In [97]:
df.to_csv(r'C:\Users\Owner\OneDrive\Desktop\Python\Arsenal Data Scraping\PL_Fixtures_23_24.csv', index=False)